# Generated by Django 5.1.6 on 2026-09-12 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_property_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('condo', 'Condo'), ('townhouse', 'Townhouse'), ('commercial', 'Commercial'), ('studio', 'Studio'), ('office', 'Office'), ('vehicle', 'Vehicle'), ('equipment', 'Equipment')], default='apartment', max_length=32),
        ),
    ]
