# Generated by Django 5.1.3 on 2026-09-13 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_maintenancerequest_ticket_number_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerequest',
            name='urgency',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent'), ('critical', 'Critical')], default='medium', max_length=16),
        ),
    ]
